# Generated by Django 4.2 on 2025-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
