# Generated by Django 4.2 on 2025-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_verifytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyTable',
        ),
    ]
