# Generated by Django 4.2 on 2025-01-24 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_remove_cart_user_id_cart_purchased_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtable',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationtable',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
