# Generated by Django 4.2 on 2025-01-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_navigationlink_homepagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
