# Generated by Django 4.2 on 2025-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_delete_homepagecontent_delete_navigationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'editable_content',
            },
        ),
    ]
