# Generated by Django 4.2 on 2025-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_editablecontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='editablecontent',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='editablecontent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
