# Generated by Django 4.2 on 2025-01-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_editablecontent2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditableContent2',
        ),
    ]
