# Generated by Django 4.2 on 2025-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_delete_editablecontent2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home2edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('subtitle', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'home2edit',
            },
        ),
    ]
